version: '3'

services:
  videos-api:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    networks:
      - videos-network
    env_file: .env
    environment:
      - DB_USER=$DB_USER
      - DB_PASSWORD=$DB_PASSWORD
      - DB_HOST=$DB_HOST
      - DB_NAME=$DB_NAME
    ports:
      - '8080:3000'
    volumes:
      - .:/home/node/app
      - node_modules:/home/node/app/node_modules

  videos-db:
    image: mongo
    restart: unless-stopped
    env_file: .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$DB_USER
      - MONGO_INITDB_ROOT_PASSWORD=$DB_PASSWORD
    volumes:
      - dbdata:/data/db
    networks:
      - videos-network
networks:
  videos-network:
    driver: bridge

volumes:
  dbdata:
  node_modules:
